#!/bin/bash

echo ""
echo "Applying migration ConfirmAmendReturn"

echo "Adding routes to conf/app.routes"

echo "" >> ../conf/app.routes
echo "GET        /confirmAmendReturn                        controllers.ConfirmAmendReturnController.onPageLoad(mode: Mode = NormalMode)" >> ../conf/app.routes
echo "POST       /confirmAmendReturn                        controllers.ConfirmAmendReturnController.onSubmit(mode: Mode = NormalMode)" >> ../conf/app.routes

echo "GET        /changeConfirmAmendReturn                  controllers.ConfirmAmendReturnController.onPageLoad(mode: Mode = CheckMode)" >> ../conf/app.routes
echo "POST       /changeConfirmAmendReturn                  controllers.ConfirmAmendReturnController.onSubmit(mode: Mode = CheckMode)" >> ../conf/app.routes

echo "Adding messages to conf.messages"
echo "" >> ../conf/messages.en
echo "confirmAmendReturn.title = confirmAmendReturn" >> ../conf/messages.en
echo "confirmAmendReturn.heading = confirmAmendReturn" >> ../conf/messages.en
echo "confirmAmendReturn.checkYourAnswersLabel = confirmAmendReturn" >> ../conf/messages.en
echo "confirmAmendReturn.error.required = Select yes if confirmAmendReturn" >> ../conf/messages.en
echo "confirmAmendReturn.change.hidden = ConfirmAmendReturn" >> ../conf/messages.en

echo "Adding to UserAnswersEntryGenerators"
awk '/trait UserAnswersEntryGenerators/ {\
    print;\
    print "";\
    print "  implicit lazy val arbitraryConfirmAmendReturnUserAnswersEntry: Arbitrary[(ConfirmAmendReturnPage.type, JsValue)] =";\
    print "    Arbitrary {";\
    print "      for {";\
    print "        page  <- arbitrary[ConfirmAmendReturnPage.type]";\
    print "        value <- arbitrary[Boolean].map(Json.toJson(_))";\
    print "      } yield (page, value)";\
    print "    }";\
    next }1' ../test-utils/generators/UserAnswersEntryGenerators.scala > tmp && mv tmp ../test-utils/generators/UserAnswersEntryGenerators.scala

echo "Adding to PageGenerators"
awk '/trait PageGenerators/ {\
    print;\
    print "";\
    print "  implicit lazy val arbitraryConfirmAmendReturnPage: Arbitrary[ConfirmAmendReturnPage.type] =";\
    print "    Arbitrary(ConfirmAmendReturnPage)";\
    next }1' ../test-utils/generators/PageGenerators.scala > tmp && mv tmp ../test-utils/generators/PageGenerators.scala

echo "Adding to UserAnswersGenerator"
awk '/val generators/ {\
    print;\
    print "    arbitrary[(ConfirmAmendReturnPage.type, JsValue)] ::";\
    next }1' ../test-utils/generators/UserAnswersGenerator.scala > tmp && mv tmp ../test-utils/generators/UserAnswersGenerator.scala

echo "Migration ConfirmAmendReturn completed"
